#!/usr/bin/env bash
# Create gitignored Firebase client config from examples, or from env when set.
# Does not print key values.
#   FIREBASE_WEB_API_KEY, FIREBASE_ANDROID_API_KEY, FIREBASE_IOS_API_KEY
#   REQUIRE_FIREBASE_KEYS=1  fail if placeholders are still in place
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
CONFIG="$ROOT/firebase_config"

write_secrets_dart() {
  local dest="$ROOT/lib/firebase_local_secrets.dart"
  if [[ -n "${FIREBASE_WEB_API_KEY:-}" && -n "${FIREBASE_ANDROID_API_KEY:-}" && -n "${FIREBASE_IOS_API_KEY:-}" ]]; then
    mkdir -p "$(dirname "$dest")"
    cat >"$dest" <<EOF
/// Generated by tool/ensure_firebase_config.sh. Gitignored.
class FirebaseLocalSecrets {
  static const String webApiKey = '${FIREBASE_WEB_API_KEY}';
  static const String androidApiKey = '${FIREBASE_ANDROID_API_KEY}';
  static const String iosApiKey = '${FIREBASE_IOS_API_KEY}';
}
EOF
    return
  fi
  if [[ ! -f "$dest" ]]; then
    cp "$CONFIG/firebase_local_secrets.example.dart" "$dest"
  fi
}

write_from_example() {
  local dest="$1"
  local example="$2"
  local key="${3:-}"
  if [[ -n "$key" ]]; then
    mkdir -p "$(dirname "$dest")"
    sed "s|YOUR_FIREBASE_API_KEY|${key}|g" "$example" >"$dest"
    return
  fi
  if [[ ! -f "$dest" ]]; then
    mkdir -p "$(dirname "$dest")"
    cp "$example" "$dest"
  fi
}

write_secrets_dart
write_from_example \
  "$ROOT/ios/Runner/GoogleService-Info.plist" \
  "$CONFIG/GoogleService-Info.example.plist" \
  "${FIREBASE_IOS_API_KEY:-}"
write_from_example \
  "$ROOT/macos/Runner/GoogleService-Info.plist" \
  "$CONFIG/GoogleService-Info.example.plist" \
  "${FIREBASE_IOS_API_KEY:-}"
write_from_example \
  "$ROOT/android/app/google-services.json" \
  "$CONFIG/google-services.example.json" \
  "${FIREBASE_ANDROID_API_KEY:-}"

if [[ "${REQUIRE_FIREBASE_KEYS:-}" == "1" ]]; then
  if grep -q "YOUR_FIREBASE_API_KEY" \
    "$ROOT/ios/Runner/GoogleService-Info.plist" \
    "$ROOT/macos/Runner/GoogleService-Info.plist" \
    "$ROOT/android/app/google-services.json" \
    || grep -q "webApiKey = '';" "$ROOT/lib/firebase_local_secrets.dart"; then
    echo "Firebase API keys are not configured." >&2
    echo "Set FIREBASE_WEB_API_KEY, FIREBASE_ANDROID_API_KEY, and FIREBASE_IOS_API_KEY." >&2
    exit 1
  fi
fi
